cc_binary(
  name = "egg_client_test",
  srcs = [
    "egg_client.h",
    "egg_client.cc",
    "egg_client_mock.h",
    "egg_client_test.cc",
  ],
  deps = [
    "@git_googletest//:gtest",
    "@git_googletest//:gtest_main",    
  ],
)