package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "auto_factory_test",
  srcs = [
    "auto_factory.h",
    "auto_factory_test.cc",
  ],
  copts = [
    "-Wno-unused-function",
    "-Wno-unused-but-set-variable",
  ],
  deps = [],
)