// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tutorial {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class AddressBook;

// ===================================================================

class AddressBook : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tutorial.AddressBook) */ {
 public:
  AddressBook();
  virtual ~AddressBook();

  AddressBook(const AddressBook& from);

  inline AddressBook& operator=(const AddressBook& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddressBook& default_instance();

  void Swap(AddressBook* other);

  // implements Message ----------------------------------------------

  inline AddressBook* New() const { return New(NULL); }

  AddressBook* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddressBook& from);
  void MergeFrom(const AddressBook& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AddressBook* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::uint32 a() const;
  void set_a(::google::protobuf::uint32 value);

  // optional uint64 uniq_id = 2;
  bool has_uniq_id() const;
  void clear_uniq_id();
  static const int kUniqIdFieldNumber = 2;
  ::google::protobuf::uint64 uniq_id() const;
  void set_uniq_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:tutorial.AddressBook)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_uniq_id();
  inline void clear_has_uniq_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 uniq_id_;
  ::google::protobuf::uint32 a_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static AddressBook* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AddressBook

// optional uint32 a = 1;
inline bool AddressBook::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddressBook::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddressBook::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddressBook::clear_a() {
  a_ = 0u;
  clear_has_a();
}
inline ::google::protobuf::uint32 AddressBook::a() const {
  // @@protoc_insertion_point(field_get:tutorial.AddressBook.a)
  return a_;
}
inline void AddressBook::set_a(::google::protobuf::uint32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:tutorial.AddressBook.a)
}

// optional uint64 uniq_id = 2;
inline bool AddressBook::has_uniq_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AddressBook::set_has_uniq_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AddressBook::clear_has_uniq_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AddressBook::clear_uniq_id() {
  uniq_id_ = GOOGLE_ULONGLONG(0);
  clear_has_uniq_id();
}
inline ::google::protobuf::uint64 AddressBook::uniq_id() const {
  // @@protoc_insertion_point(field_get:tutorial.AddressBook.uniq_id)
  return uniq_id_;
}
inline void AddressBook::set_uniq_id(::google::protobuf::uint64 value) {
  set_has_uniq_id();
  uniq_id_ = value;
  // @@protoc_insertion_point(field_set:tutorial.AddressBook.uniq_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
