// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp/score.proto

#include "temp/score.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_temp_2fscore_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_temp_2fscore_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Scores;
}  // namespace protobuf_temp_2fscore_2eproto
namespace antpath {
namespace predictor {
class ScoresDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Scores>
      _instance;
} _Scores_default_instance_;
class ItemRankScoreDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ItemRankScore>
      _instance;
} _ItemRankScore_default_instance_;
}  // namespace predictor
}  // namespace antpath
namespace protobuf_temp_2fscore_2eproto {
static void InitDefaultsScores() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::antpath::predictor::_Scores_default_instance_;
    new (ptr) ::antpath::predictor::Scores();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::antpath::predictor::Scores::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Scores =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsScores}, {}};

static void InitDefaultsItemRankScore() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::antpath::predictor::_ItemRankScore_default_instance_;
    new (ptr) ::antpath::predictor::ItemRankScore();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::antpath::predictor::ItemRankScore::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ItemRankScore =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsItemRankScore}, {
      &protobuf_temp_2fscore_2eproto::scc_info_Scores.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Scores.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ItemRankScore.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::Scores, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::Scores, embedx_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::ItemRankScore, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::ItemRankScore, item_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::ItemRankScore, rank_score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::ItemRankScore, uniq_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::antpath::predictor::ItemRankScore, mlt_rank_scores_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::antpath::predictor::Scores)},
  { 6, -1, sizeof(::antpath::predictor::ItemRankScore)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::antpath::predictor::_Scores_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::antpath::predictor::_ItemRankScore_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "temp/score.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020temp/score.proto\022\021antpath.predictor\"\030\n"
      "\006Scores\022\016\n\006embedx\030\001 \003(\002\"y\n\rItemRankScore"
      "\022\017\n\007item_id\030\001 \001(\t\022\022\n\nrank_score\030\002 \003(\002\022\017\n"
      "\007uniq_id\030\003 \001(\004\0222\n\017mlt_rank_scores\030\004 \003(\0132"
      "\031.antpath.predictor.ScoresB&Z$git.woa.co"
      "m/comp_video/proto/rankingb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 234);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "temp/score.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_temp_2fscore_2eproto
namespace antpath {
namespace predictor {

// ===================================================================

void Scores::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Scores::kEmbedxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Scores::Scores()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_temp_2fscore_2eproto::scc_info_Scores.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:antpath.predictor.Scores)
}
Scores::Scores(const Scores& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      embedx_(from.embedx_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:antpath.predictor.Scores)
}

void Scores::SharedCtor() {
}

Scores::~Scores() {
  // @@protoc_insertion_point(destructor:antpath.predictor.Scores)
  SharedDtor();
}

void Scores::SharedDtor() {
}

void Scores::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Scores::descriptor() {
  ::protobuf_temp_2fscore_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_temp_2fscore_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Scores& Scores::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_temp_2fscore_2eproto::scc_info_Scores.base);
  return *internal_default_instance();
}


void Scores::Clear() {
// @@protoc_insertion_point(message_clear_start:antpath.predictor.Scores)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  embedx_.Clear();
  _internal_metadata_.Clear();
}

bool Scores::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:antpath.predictor.Scores)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float embedx = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_embedx())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_embedx())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:antpath.predictor.Scores)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:antpath.predictor.Scores)
  return false;
#undef DO_
}

void Scores::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:antpath.predictor.Scores)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float embedx = 1;
  if (this->embedx_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _embedx_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->embedx().data(), this->embedx_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:antpath.predictor.Scores)
}

::google::protobuf::uint8* Scores::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:antpath.predictor.Scores)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float embedx = 1;
  if (this->embedx_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _embedx_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->embedx_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:antpath.predictor.Scores)
  return target;
}

size_t Scores::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:antpath.predictor.Scores)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float embedx = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->embedx_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _embedx_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Scores::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:antpath.predictor.Scores)
  GOOGLE_DCHECK_NE(&from, this);
  const Scores* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Scores>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:antpath.predictor.Scores)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:antpath.predictor.Scores)
    MergeFrom(*source);
  }
}

void Scores::MergeFrom(const Scores& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:antpath.predictor.Scores)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  embedx_.MergeFrom(from.embedx_);
}

void Scores::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:antpath.predictor.Scores)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Scores::CopyFrom(const Scores& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:antpath.predictor.Scores)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Scores::IsInitialized() const {
  return true;
}

void Scores::Swap(Scores* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Scores::InternalSwap(Scores* other) {
  using std::swap;
  embedx_.InternalSwap(&other->embedx_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Scores::GetMetadata() const {
  protobuf_temp_2fscore_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_temp_2fscore_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ItemRankScore::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemRankScore::kItemIdFieldNumber;
const int ItemRankScore::kRankScoreFieldNumber;
const int ItemRankScore::kUniqIdFieldNumber;
const int ItemRankScore::kMltRankScoresFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemRankScore::ItemRankScore()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_temp_2fscore_2eproto::scc_info_ItemRankScore.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:antpath.predictor.ItemRankScore)
}
ItemRankScore::ItemRankScore(const ItemRankScore& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      rank_score_(from.rank_score_),
      mlt_rank_scores_(from.mlt_rank_scores_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  item_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.item_id().size() > 0) {
    item_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.item_id_);
  }
  uniq_id_ = from.uniq_id_;
  // @@protoc_insertion_point(copy_constructor:antpath.predictor.ItemRankScore)
}

void ItemRankScore::SharedCtor() {
  item_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uniq_id_ = GOOGLE_ULONGLONG(0);
}

ItemRankScore::~ItemRankScore() {
  // @@protoc_insertion_point(destructor:antpath.predictor.ItemRankScore)
  SharedDtor();
}

void ItemRankScore::SharedDtor() {
  item_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ItemRankScore::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ItemRankScore::descriptor() {
  ::protobuf_temp_2fscore_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_temp_2fscore_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ItemRankScore& ItemRankScore::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_temp_2fscore_2eproto::scc_info_ItemRankScore.base);
  return *internal_default_instance();
}


void ItemRankScore::Clear() {
// @@protoc_insertion_point(message_clear_start:antpath.predictor.ItemRankScore)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rank_score_.Clear();
  mlt_rank_scores_.Clear();
  item_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uniq_id_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool ItemRankScore::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:antpath.predictor.ItemRankScore)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string item_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_item_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->item_id().data(), static_cast<int>(this->item_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "antpath.predictor.ItemRankScore.item_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float rank_score = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_rank_score())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 18u, input, this->mutable_rank_score())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 uniq_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &uniq_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .antpath.predictor.Scores mlt_rank_scores = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_mlt_rank_scores()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:antpath.predictor.ItemRankScore)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:antpath.predictor.ItemRankScore)
  return false;
#undef DO_
}

void ItemRankScore::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:antpath.predictor.ItemRankScore)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string item_id = 1;
  if (this->item_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->item_id().data(), static_cast<int>(this->item_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "antpath.predictor.ItemRankScore.item_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->item_id(), output);
  }

  // repeated float rank_score = 2;
  if (this->rank_score_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _rank_score_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->rank_score().data(), this->rank_score_size(), output);
  }

  // uint64 uniq_id = 3;
  if (this->uniq_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->uniq_id(), output);
  }

  // repeated .antpath.predictor.Scores mlt_rank_scores = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->mlt_rank_scores_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->mlt_rank_scores(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:antpath.predictor.ItemRankScore)
}

::google::protobuf::uint8* ItemRankScore::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:antpath.predictor.ItemRankScore)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string item_id = 1;
  if (this->item_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->item_id().data(), static_cast<int>(this->item_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "antpath.predictor.ItemRankScore.item_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->item_id(), target);
  }

  // repeated float rank_score = 2;
  if (this->rank_score_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _rank_score_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->rank_score_, target);
  }

  // uint64 uniq_id = 3;
  if (this->uniq_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->uniq_id(), target);
  }

  // repeated .antpath.predictor.Scores mlt_rank_scores = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->mlt_rank_scores_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->mlt_rank_scores(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:antpath.predictor.ItemRankScore)
  return target;
}

size_t ItemRankScore::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:antpath.predictor.ItemRankScore)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float rank_score = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->rank_score_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _rank_score_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated .antpath.predictor.Scores mlt_rank_scores = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->mlt_rank_scores_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->mlt_rank_scores(static_cast<int>(i)));
    }
  }

  // string item_id = 1;
  if (this->item_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->item_id());
  }

  // uint64 uniq_id = 3;
  if (this->uniq_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->uniq_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ItemRankScore::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:antpath.predictor.ItemRankScore)
  GOOGLE_DCHECK_NE(&from, this);
  const ItemRankScore* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ItemRankScore>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:antpath.predictor.ItemRankScore)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:antpath.predictor.ItemRankScore)
    MergeFrom(*source);
  }
}

void ItemRankScore::MergeFrom(const ItemRankScore& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:antpath.predictor.ItemRankScore)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  rank_score_.MergeFrom(from.rank_score_);
  mlt_rank_scores_.MergeFrom(from.mlt_rank_scores_);
  if (from.item_id().size() > 0) {

    item_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.item_id_);
  }
  if (from.uniq_id() != 0) {
    set_uniq_id(from.uniq_id());
  }
}

void ItemRankScore::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:antpath.predictor.ItemRankScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemRankScore::CopyFrom(const ItemRankScore& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:antpath.predictor.ItemRankScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemRankScore::IsInitialized() const {
  return true;
}

void ItemRankScore::Swap(ItemRankScore* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemRankScore::InternalSwap(ItemRankScore* other) {
  using std::swap;
  rank_score_.InternalSwap(&other->rank_score_);
  CastToBase(&mlt_rank_scores_)->InternalSwap(CastToBase(&other->mlt_rank_scores_));
  item_id_.Swap(&other->item_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(uniq_id_, other->uniq_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ItemRankScore::GetMetadata() const {
  protobuf_temp_2fscore_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_temp_2fscore_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace predictor
}  // namespace antpath
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::antpath::predictor::Scores* Arena::CreateMaybeMessage< ::antpath::predictor::Scores >(Arena* arena) {
  return Arena::CreateInternal< ::antpath::predictor::Scores >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::antpath::predictor::ItemRankScore* Arena::CreateMaybeMessage< ::antpath::predictor::ItemRankScore >(Arena* arena) {
  return Arena::CreateInternal< ::antpath::predictor::ItemRankScore >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
